repos:
  # Some out-of-the-box hooks for pre-commit.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-vcs-permalinks
      - id: check-case-conflict
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  # Static checker for GitHub Actions workflow files.
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint

  # Optimize .png files.
  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.0.0
    hooks:
      - id: oxipng
